name = "dabot"
main = "dabot.py"
compatibility_date = "2026-04-18"
compatibility_flags = ["python_workers"]
workers_dev = true

# This sets up your 30-minute background task
[triggers]
crons = ["*/30 * * * *"]
